// Code generated by protoc-gen-deepcopy. DO NOT EDIT.
package v1

import (
	proto "google.golang.org/protobuf/proto"
)

// DeepCopyInto supports using Config within kubernetes types, where deepcopy-gen is used.
func (in *Config) DeepCopyInto(out *Config) {
	p := proto.Clone(in).(*Config)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Config. Required by controller-gen.
func (in *Config) DeepCopy() *Config {
	if in == nil {
		return nil
	}
	out := new(Config)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new Config. Required by controller-gen.
func (in *Config) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using BackupState within kubernetes types, where deepcopy-gen is used.
func (in *BackupState) DeepCopyInto(out *BackupState) {
	p := proto.Clone(in).(*BackupState)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackupState. Required by controller-gen.
func (in *BackupState) DeepCopy() *BackupState {
	if in == nil {
		return nil
	}
	out := new(BackupState)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new BackupState. Required by controller-gen.
func (in *BackupState) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using Schedule within kubernetes types, where deepcopy-gen is used.
func (in *Schedule) DeepCopyInto(out *Schedule) {
	p := proto.Clone(in).(*Schedule)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Schedule. Required by controller-gen.
func (in *Schedule) DeepCopy() *Schedule {
	if in == nil {
		return nil
	}
	out := new(Schedule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new Schedule. Required by controller-gen.
func (in *Schedule) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using Repeat within kubernetes types, where deepcopy-gen is used.
func (in *Repeat) DeepCopyInto(out *Repeat) {
	p := proto.Clone(in).(*Repeat)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Repeat. Required by controller-gen.
func (in *Repeat) DeepCopy() *Repeat {
	if in == nil {
		return nil
	}
	out := new(Repeat)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new Repeat. Required by controller-gen.
func (in *Repeat) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using Repeat_Other within kubernetes types, where deepcopy-gen is used.
func (in *Repeat_Other) DeepCopyInto(out *Repeat_Other) {
	p := proto.Clone(in).(*Repeat_Other)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Repeat_Other. Required by controller-gen.
func (in *Repeat_Other) DeepCopy() *Repeat_Other {
	if in == nil {
		return nil
	}
	out := new(Repeat_Other)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new Repeat_Other. Required by controller-gen.
func (in *Repeat_Other) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}
