// Code generated by protoc-gen-jsonshim. DO NOT EDIT.
package v1

import (
	bytes "bytes"
	jsonpb "github.com/golang/protobuf/jsonpb"
)

// MarshalJSON is a custom marshaler for Schedule
func (this *Schedule) MarshalJSON() ([]byte, error) {
	str, err := CoreMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for Schedule
func (this *Schedule) UnmarshalJSON(b []byte) error {
	return CoreUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for ExpectCluster
func (this *ExpectCluster) MarshalJSON() ([]byte, error) {
	str, err := CoreMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for ExpectCluster
func (this *ExpectCluster) UnmarshalJSON(b []byte) error {
	return CoreUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for Repeat
func (this *Repeat) MarshalJSON() ([]byte, error) {
	str, err := CoreMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for Repeat
func (this *Repeat) UnmarshalJSON(b []byte) error {
	return CoreUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for Repeat_Other
func (this *Repeat_Other) MarshalJSON() ([]byte, error) {
	str, err := CoreMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for Repeat_Other
func (this *Repeat_Other) UnmarshalJSON(b []byte) error {
	return CoreUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

var (
	CoreMarshaler   = &jsonpb.Marshaler{}
	CoreUnmarshaler = &jsonpb.Unmarshaler{AllowUnknownFields: true}
)
