// Code generated by protoc-gen-deepcopy. DO NOT EDIT.
package v1

import (
	proto "google.golang.org/protobuf/proto"
)

// DeepCopyInto supports using Config within kubernetes types, where deepcopy-gen is used.
func (in *Config) DeepCopyInto(out *Config) {
	p := proto.Clone(in).(*Config)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Config. Required by controller-gen.
func (in *Config) DeepCopy() *Config {
	if in == nil {
		return nil
	}
	out := new(Config)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new Config. Required by controller-gen.
func (in *Config) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using Schedule within kubernetes types, where deepcopy-gen is used.
func (in *Schedule) DeepCopyInto(out *Schedule) {
	p := proto.Clone(in).(*Schedule)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Schedule. Required by controller-gen.
func (in *Schedule) DeepCopy() *Schedule {
	if in == nil {
		return nil
	}
	out := new(Schedule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new Schedule. Required by controller-gen.
func (in *Schedule) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using Except within kubernetes types, where deepcopy-gen is used.
func (in *Except) DeepCopyInto(out *Except) {
	p := proto.Clone(in).(*Except)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Except. Required by controller-gen.
func (in *Except) DeepCopy() *Except {
	if in == nil {
		return nil
	}
	out := new(Except)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new Except. Required by controller-gen.
func (in *Except) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using Except_Cluster within kubernetes types, where deepcopy-gen is used.
func (in *Except_Cluster) DeepCopyInto(out *Except_Cluster) {
	p := proto.Clone(in).(*Except_Cluster)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Except_Cluster. Required by controller-gen.
func (in *Except_Cluster) DeepCopy() *Except_Cluster {
	if in == nil {
		return nil
	}
	out := new(Except_Cluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new Except_Cluster. Required by controller-gen.
func (in *Except_Cluster) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using Except_Sql within kubernetes types, where deepcopy-gen is used.
func (in *Except_Sql) DeepCopyInto(out *Except_Sql) {
	p := proto.Clone(in).(*Except_Sql)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Except_Sql. Required by controller-gen.
func (in *Except_Sql) DeepCopy() *Except_Sql {
	if in == nil {
		return nil
	}
	out := new(Except_Sql)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new Except_Sql. Required by controller-gen.
func (in *Except_Sql) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using Except_Vm within kubernetes types, where deepcopy-gen is used.
func (in *Except_Vm) DeepCopyInto(out *Except_Vm) {
	p := proto.Clone(in).(*Except_Vm)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Except_Vm. Required by controller-gen.
func (in *Except_Vm) DeepCopy() *Except_Vm {
	if in == nil {
		return nil
	}
	out := new(Except_Vm)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new Except_Vm. Required by controller-gen.
func (in *Except_Vm) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using Repeat within kubernetes types, where deepcopy-gen is used.
func (in *Repeat) DeepCopyInto(out *Repeat) {
	p := proto.Clone(in).(*Repeat)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Repeat. Required by controller-gen.
func (in *Repeat) DeepCopy() *Repeat {
	if in == nil {
		return nil
	}
	out := new(Repeat)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new Repeat. Required by controller-gen.
func (in *Repeat) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using Repeat_Other within kubernetes types, where deepcopy-gen is used.
func (in *Repeat_Other) DeepCopyInto(out *Repeat_Other) {
	p := proto.Clone(in).(*Repeat_Other)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Repeat_Other. Required by controller-gen.
func (in *Repeat_Other) DeepCopy() *Repeat_Other {
	if in == nil {
		return nil
	}
	out := new(Repeat_Other)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new Repeat_Other. Required by controller-gen.
func (in *Repeat_Other) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}
