// Code generated by protoc-gen-jsonshim. DO NOT EDIT.
package v1

import (
	bytes "bytes"
	jsonpb "github.com/golang/protobuf/jsonpb"
)

// MarshalJSON is a custom marshaler for Config
func (this *Config) MarshalJSON() ([]byte, error) {
	str, err := CoreMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for Config
func (this *Config) UnmarshalJSON(b []byte) error {
	return CoreUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for Schedule
func (this *Schedule) MarshalJSON() ([]byte, error) {
	str, err := CoreMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for Schedule
func (this *Schedule) UnmarshalJSON(b []byte) error {
	return CoreUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for Except
func (this *Except) MarshalJSON() ([]byte, error) {
	str, err := CoreMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for Except
func (this *Except) UnmarshalJSON(b []byte) error {
	return CoreUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for Except_Cluster
func (this *Except_Cluster) MarshalJSON() ([]byte, error) {
	str, err := CoreMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for Except_Cluster
func (this *Except_Cluster) UnmarshalJSON(b []byte) error {
	return CoreUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for Except_Sql
func (this *Except_Sql) MarshalJSON() ([]byte, error) {
	str, err := CoreMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for Except_Sql
func (this *Except_Sql) UnmarshalJSON(b []byte) error {
	return CoreUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for Except_Vm
func (this *Except_Vm) MarshalJSON() ([]byte, error) {
	str, err := CoreMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for Except_Vm
func (this *Except_Vm) UnmarshalJSON(b []byte) error {
	return CoreUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for Repeat
func (this *Repeat) MarshalJSON() ([]byte, error) {
	str, err := CoreMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for Repeat
func (this *Repeat) UnmarshalJSON(b []byte) error {
	return CoreUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for Repeat_Other
func (this *Repeat_Other) MarshalJSON() ([]byte, error) {
	str, err := CoreMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for Repeat_Other
func (this *Repeat_Other) UnmarshalJSON(b []byte) error {
	return CoreUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

var (
	CoreMarshaler   = &jsonpb.Marshaler{}
	CoreUnmarshaler = &jsonpb.Unmarshaler{AllowUnknownFields: true}
)
