// Code generated by protoc-gen-deepcopy. DO NOT EDIT.
package v1

import (
	proto "google.golang.org/protobuf/proto"
)

// DeepCopyInto supports using Resource within kubernetes types, where deepcopy-gen is used.
func (in *Resource) DeepCopyInto(out *Resource) {
	p := proto.Clone(in).(*Resource)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Resource. Required by controller-gen.
func (in *Resource) DeepCopy() *Resource {
	if in == nil {
		return nil
	}
	out := new(Resource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new Resource. Required by controller-gen.
func (in *Resource) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using Cluster within kubernetes types, where deepcopy-gen is used.
func (in *Cluster) DeepCopyInto(out *Cluster) {
	p := proto.Clone(in).(*Cluster)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Cluster. Required by controller-gen.
func (in *Cluster) DeepCopy() *Cluster {
	if in == nil {
		return nil
	}
	out := new(Cluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new Cluster. Required by controller-gen.
func (in *Cluster) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using Cluster_NodePool within kubernetes types, where deepcopy-gen is used.
func (in *Cluster_NodePool) DeepCopyInto(out *Cluster_NodePool) {
	p := proto.Clone(in).(*Cluster_NodePool)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Cluster_NodePool. Required by controller-gen.
func (in *Cluster_NodePool) DeepCopy() *Cluster_NodePool {
	if in == nil {
		return nil
	}
	out := new(Cluster_NodePool)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new Cluster_NodePool. Required by controller-gen.
func (in *Cluster_NodePool) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using Cluster_NodePool_AutoScaling within kubernetes types, where deepcopy-gen is used.
func (in *Cluster_NodePool_AutoScaling) DeepCopyInto(out *Cluster_NodePool_AutoScaling) {
	p := proto.Clone(in).(*Cluster_NodePool_AutoScaling)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Cluster_NodePool_AutoScaling. Required by controller-gen.
func (in *Cluster_NodePool_AutoScaling) DeepCopy() *Cluster_NodePool_AutoScaling {
	if in == nil {
		return nil
	}
	out := new(Cluster_NodePool_AutoScaling)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new Cluster_NodePool_AutoScaling. Required by controller-gen.
func (in *Cluster_NodePool_AutoScaling) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using Sql within kubernetes types, where deepcopy-gen is used.
func (in *Sql) DeepCopyInto(out *Sql) {
	p := proto.Clone(in).(*Sql)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Sql. Required by controller-gen.
func (in *Sql) DeepCopy() *Sql {
	if in == nil {
		return nil
	}
	out := new(Sql)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new Sql. Required by controller-gen.
func (in *Sql) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using Vm within kubernetes types, where deepcopy-gen is used.
func (in *Vm) DeepCopyInto(out *Vm) {
	p := proto.Clone(in).(*Vm)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Vm. Required by controller-gen.
func (in *Vm) DeepCopy() *Vm {
	if in == nil {
		return nil
	}
	out := new(Vm)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new Vm. Required by controller-gen.
func (in *Vm) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}
