// Code generated by protoc-gen-go. DO NOT EDIT.
// source: apis/v1/resource.proto

package v1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Resource struct {
	// Types that are valid to be assigned to Specifier:
	//	*Resource_Cluster
	//	*Resource_Sql
	//	*Resource_Vm
	Specifier            isResource_Specifier   `protobuf_oneof:"specifier"`
	PausedAt             *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=paused_at,json=pausedAt,proto3" json:"paused_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *Resource) Reset()         { *m = Resource{} }
func (m *Resource) String() string { return proto.CompactTextString(m) }
func (*Resource) ProtoMessage()    {}
func (*Resource) Descriptor() ([]byte, []int) {
	return fileDescriptor_37f1d1a974ae4635, []int{0}
}

func (m *Resource) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Resource.Unmarshal(m, b)
}
func (m *Resource) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Resource.Marshal(b, m, deterministic)
}
func (m *Resource) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Resource.Merge(m, src)
}
func (m *Resource) XXX_Size() int {
	return xxx_messageInfo_Resource.Size(m)
}
func (m *Resource) XXX_DiscardUnknown() {
	xxx_messageInfo_Resource.DiscardUnknown(m)
}

var xxx_messageInfo_Resource proto.InternalMessageInfo

type isResource_Specifier interface {
	isResource_Specifier()
}

type Resource_Cluster struct {
	Cluster *Cluster `protobuf:"bytes,1,opt,name=cluster,proto3,oneof"`
}

type Resource_Sql struct {
	Sql *Sql `protobuf:"bytes,2,opt,name=sql,proto3,oneof"`
}

type Resource_Vm struct {
	Vm *Vm `protobuf:"bytes,3,opt,name=vm,proto3,oneof"`
}

func (*Resource_Cluster) isResource_Specifier() {}

func (*Resource_Sql) isResource_Specifier() {}

func (*Resource_Vm) isResource_Specifier() {}

func (m *Resource) GetSpecifier() isResource_Specifier {
	if m != nil {
		return m.Specifier
	}
	return nil
}

func (m *Resource) GetCluster() *Cluster {
	if x, ok := m.GetSpecifier().(*Resource_Cluster); ok {
		return x.Cluster
	}
	return nil
}

func (m *Resource) GetSql() *Sql {
	if x, ok := m.GetSpecifier().(*Resource_Sql); ok {
		return x.Sql
	}
	return nil
}

func (m *Resource) GetVm() *Vm {
	if x, ok := m.GetSpecifier().(*Resource_Vm); ok {
		return x.Vm
	}
	return nil
}

func (m *Resource) GetPausedAt() *timestamppb.Timestamp {
	if m != nil {
		return m.PausedAt
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Resource) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Resource_Cluster)(nil),
		(*Resource_Sql)(nil),
		(*Resource_Vm)(nil),
	}
}

type Cluster struct {
	Project              string              `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	Name                 string              `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Location             string              `protobuf:"bytes,3,opt,name=location,proto3" json:"location,omitempty"`
	NodePools            []*Cluster_NodePool `protobuf:"bytes,4,rep,name=node_pools,json=nodePools,proto3" json:"node_pools,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *Cluster) Reset()         { *m = Cluster{} }
func (m *Cluster) String() string { return proto.CompactTextString(m) }
func (*Cluster) ProtoMessage()    {}
func (*Cluster) Descriptor() ([]byte, []int) {
	return fileDescriptor_37f1d1a974ae4635, []int{1}
}

func (m *Cluster) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Cluster.Unmarshal(m, b)
}
func (m *Cluster) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Cluster.Marshal(b, m, deterministic)
}
func (m *Cluster) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Cluster.Merge(m, src)
}
func (m *Cluster) XXX_Size() int {
	return xxx_messageInfo_Cluster.Size(m)
}
func (m *Cluster) XXX_DiscardUnknown() {
	xxx_messageInfo_Cluster.DiscardUnknown(m)
}

var xxx_messageInfo_Cluster proto.InternalMessageInfo

func (m *Cluster) GetProject() string {
	if m != nil {
		return m.Project
	}
	return ""
}

func (m *Cluster) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Cluster) GetLocation() string {
	if m != nil {
		return m.Location
	}
	return ""
}

func (m *Cluster) GetNodePools() []*Cluster_NodePool {
	if m != nil {
		return m.NodePools
	}
	return nil
}

type Cluster_NodePool struct {
	Name                 string                        `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	InstanceGroups       []string                      `protobuf:"bytes,2,rep,name=instance_groups,json=instanceGroups,proto3" json:"instance_groups,omitempty"`
	Locations            []string                      `protobuf:"bytes,3,rep,name=locations,proto3" json:"locations,omitempty"`
	InitialNodeCount     int32                         `protobuf:"varint,4,opt,name=initial_node_count,json=initialNodeCount,proto3" json:"initial_node_count,omitempty"`
	CurrentSize          int32                         `protobuf:"varint,5,opt,name=current_size,json=currentSize,proto3" json:"current_size,omitempty"`
	Autoscaling          *Cluster_NodePool_AutoScaling `protobuf:"bytes,6,opt,name=autoscaling,proto3" json:"autoscaling,omitempty"`
	Spot                 bool                          `protobuf:"varint,7,opt,name=spot,proto3" json:"spot,omitempty"`
	Preemptible          bool                          `protobuf:"varint,8,opt,name=preemptible,proto3" json:"preemptible,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *Cluster_NodePool) Reset()         { *m = Cluster_NodePool{} }
func (m *Cluster_NodePool) String() string { return proto.CompactTextString(m) }
func (*Cluster_NodePool) ProtoMessage()    {}
func (*Cluster_NodePool) Descriptor() ([]byte, []int) {
	return fileDescriptor_37f1d1a974ae4635, []int{1, 0}
}

func (m *Cluster_NodePool) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Cluster_NodePool.Unmarshal(m, b)
}
func (m *Cluster_NodePool) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Cluster_NodePool.Marshal(b, m, deterministic)
}
func (m *Cluster_NodePool) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Cluster_NodePool.Merge(m, src)
}
func (m *Cluster_NodePool) XXX_Size() int {
	return xxx_messageInfo_Cluster_NodePool.Size(m)
}
func (m *Cluster_NodePool) XXX_DiscardUnknown() {
	xxx_messageInfo_Cluster_NodePool.DiscardUnknown(m)
}

var xxx_messageInfo_Cluster_NodePool proto.InternalMessageInfo

func (m *Cluster_NodePool) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Cluster_NodePool) GetInstanceGroups() []string {
	if m != nil {
		return m.InstanceGroups
	}
	return nil
}

func (m *Cluster_NodePool) GetLocations() []string {
	if m != nil {
		return m.Locations
	}
	return nil
}

func (m *Cluster_NodePool) GetInitialNodeCount() int32 {
	if m != nil {
		return m.InitialNodeCount
	}
	return 0
}

func (m *Cluster_NodePool) GetCurrentSize() int32 {
	if m != nil {
		return m.CurrentSize
	}
	return 0
}

func (m *Cluster_NodePool) GetAutoscaling() *Cluster_NodePool_AutoScaling {
	if m != nil {
		return m.Autoscaling
	}
	return nil
}

func (m *Cluster_NodePool) GetSpot() bool {
	if m != nil {
		return m.Spot
	}
	return false
}

func (m *Cluster_NodePool) GetPreemptible() bool {
	if m != nil {
		return m.Preemptible
	}
	return false
}

type Cluster_NodePool_AutoScaling struct {
	Enabled              bool     `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	MinNodeCount         int32    `protobuf:"varint,2,opt,name=min_node_count,json=minNodeCount,proto3" json:"min_node_count,omitempty"`
	MaxNodeCount         int32    `protobuf:"varint,3,opt,name=max_node_count,json=maxNodeCount,proto3" json:"max_node_count,omitempty"`
	Autoprovisioned      bool     `protobuf:"varint,4,opt,name=autoprovisioned,proto3" json:"autoprovisioned,omitempty"`
	LocationPolicy       string   `protobuf:"bytes,5,opt,name=location_policy,json=locationPolicy,proto3" json:"location_policy,omitempty"`
	TotalMinNodeCount    int32    `protobuf:"varint,6,opt,name=total_min_node_count,json=totalMinNodeCount,proto3" json:"total_min_node_count,omitempty"`
	TotalMaxNodeCount    int32    `protobuf:"varint,7,opt,name=total_max_node_count,json=totalMaxNodeCount,proto3" json:"total_max_node_count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Cluster_NodePool_AutoScaling) Reset()         { *m = Cluster_NodePool_AutoScaling{} }
func (m *Cluster_NodePool_AutoScaling) String() string { return proto.CompactTextString(m) }
func (*Cluster_NodePool_AutoScaling) ProtoMessage()    {}
func (*Cluster_NodePool_AutoScaling) Descriptor() ([]byte, []int) {
	return fileDescriptor_37f1d1a974ae4635, []int{1, 0, 0}
}

func (m *Cluster_NodePool_AutoScaling) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Cluster_NodePool_AutoScaling.Unmarshal(m, b)
}
func (m *Cluster_NodePool_AutoScaling) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Cluster_NodePool_AutoScaling.Marshal(b, m, deterministic)
}
func (m *Cluster_NodePool_AutoScaling) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Cluster_NodePool_AutoScaling.Merge(m, src)
}
func (m *Cluster_NodePool_AutoScaling) XXX_Size() int {
	return xxx_messageInfo_Cluster_NodePool_AutoScaling.Size(m)
}
func (m *Cluster_NodePool_AutoScaling) XXX_DiscardUnknown() {
	xxx_messageInfo_Cluster_NodePool_AutoScaling.DiscardUnknown(m)
}

var xxx_messageInfo_Cluster_NodePool_AutoScaling proto.InternalMessageInfo

func (m *Cluster_NodePool_AutoScaling) GetEnabled() bool {
	if m != nil {
		return m.Enabled
	}
	return false
}

func (m *Cluster_NodePool_AutoScaling) GetMinNodeCount() int32 {
	if m != nil {
		return m.MinNodeCount
	}
	return 0
}

func (m *Cluster_NodePool_AutoScaling) GetMaxNodeCount() int32 {
	if m != nil {
		return m.MaxNodeCount
	}
	return 0
}

func (m *Cluster_NodePool_AutoScaling) GetAutoprovisioned() bool {
	if m != nil {
		return m.Autoprovisioned
	}
	return false
}

func (m *Cluster_NodePool_AutoScaling) GetLocationPolicy() string {
	if m != nil {
		return m.LocationPolicy
	}
	return ""
}

func (m *Cluster_NodePool_AutoScaling) GetTotalMinNodeCount() int32 {
	if m != nil {
		return m.TotalMinNodeCount
	}
	return 0
}

func (m *Cluster_NodePool_AutoScaling) GetTotalMaxNodeCount() int32 {
	if m != nil {
		return m.TotalMaxNodeCount
	}
	return 0
}

type Sql struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Project              string   `protobuf:"bytes,2,opt,name=project,proto3" json:"project,omitempty"`
	Region               string   `protobuf:"bytes,3,opt,name=region,proto3" json:"region,omitempty"`
	GceZone              string   `protobuf:"bytes,4,opt,name=gce_zone,json=gceZone,proto3" json:"gce_zone,omitempty"`
	IsRunning            bool     `protobuf:"varint,5,opt,name=is_running,json=isRunning,proto3" json:"is_running,omitempty"`
	DatabaseVersion      string   `protobuf:"bytes,6,opt,name=database_version,json=databaseVersion,proto3" json:"database_version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Sql) Reset()         { *m = Sql{} }
func (m *Sql) String() string { return proto.CompactTextString(m) }
func (*Sql) ProtoMessage()    {}
func (*Sql) Descriptor() ([]byte, []int) {
	return fileDescriptor_37f1d1a974ae4635, []int{2}
}

func (m *Sql) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Sql.Unmarshal(m, b)
}
func (m *Sql) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Sql.Marshal(b, m, deterministic)
}
func (m *Sql) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Sql.Merge(m, src)
}
func (m *Sql) XXX_Size() int {
	return xxx_messageInfo_Sql.Size(m)
}
func (m *Sql) XXX_DiscardUnknown() {
	xxx_messageInfo_Sql.DiscardUnknown(m)
}

var xxx_messageInfo_Sql proto.InternalMessageInfo

func (m *Sql) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Sql) GetProject() string {
	if m != nil {
		return m.Project
	}
	return ""
}

func (m *Sql) GetRegion() string {
	if m != nil {
		return m.Region
	}
	return ""
}

func (m *Sql) GetGceZone() string {
	if m != nil {
		return m.GceZone
	}
	return ""
}

func (m *Sql) GetIsRunning() bool {
	if m != nil {
		return m.IsRunning
	}
	return false
}

func (m *Sql) GetDatabaseVersion() string {
	if m != nil {
		return m.DatabaseVersion
	}
	return ""
}

type Vm struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Zone                 string   `protobuf:"bytes,2,opt,name=zone,proto3" json:"zone,omitempty"`
	State                string   `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`
	Project              string   `protobuf:"bytes,4,opt,name=project,proto3" json:"project,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Vm) Reset()         { *m = Vm{} }
func (m *Vm) String() string { return proto.CompactTextString(m) }
func (*Vm) ProtoMessage()    {}
func (*Vm) Descriptor() ([]byte, []int) {
	return fileDescriptor_37f1d1a974ae4635, []int{3}
}

func (m *Vm) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Vm.Unmarshal(m, b)
}
func (m *Vm) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Vm.Marshal(b, m, deterministic)
}
func (m *Vm) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Vm.Merge(m, src)
}
func (m *Vm) XXX_Size() int {
	return xxx_messageInfo_Vm.Size(m)
}
func (m *Vm) XXX_DiscardUnknown() {
	xxx_messageInfo_Vm.DiscardUnknown(m)
}

var xxx_messageInfo_Vm proto.InternalMessageInfo

func (m *Vm) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Vm) GetZone() string {
	if m != nil {
		return m.Zone
	}
	return ""
}

func (m *Vm) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *Vm) GetProject() string {
	if m != nil {
		return m.Project
	}
	return ""
}

func init() {
	proto.RegisterType((*Resource)(nil), "apis.v1.Resource")
	proto.RegisterType((*Cluster)(nil), "apis.v1.Cluster")
	proto.RegisterType((*Cluster_NodePool)(nil), "apis.v1.Cluster.NodePool")
	proto.RegisterType((*Cluster_NodePool_AutoScaling)(nil), "apis.v1.Cluster.NodePool.AutoScaling")
	proto.RegisterType((*Sql)(nil), "apis.v1.Sql")
	proto.RegisterType((*Vm)(nil), "apis.v1.Vm")
}

func init() {
	proto.RegisterFile("apis/v1/resource.proto", fileDescriptor_37f1d1a974ae4635)
}

var fileDescriptor_37f1d1a974ae4635 = []byte{
	// 706 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x54, 0xdd, 0x4e, 0xdc, 0x38,
	0x18, 0x65, 0x32, 0x7f, 0xc9, 0x17, 0x04, 0xac, 0x85, 0x50, 0x18, 0x2d, 0xda, 0xd9, 0xd1, 0xae,
	0x76, 0x56, 0x82, 0x44, 0xc0, 0x45, 0x7b, 0x0b, 0x5c, 0xc0, 0x4d, 0x2b, 0xe4, 0xa9, 0xb8, 0x40,
	0x95, 0x22, 0x4f, 0xe6, 0x23, 0xb8, 0x4d, 0xec, 0x10, 0x3b, 0x23, 0xca, 0x13, 0xf5, 0xb2, 0x6f,
	0xd0, 0x57, 0xe9, 0x23, 0xf4, 0x11, 0xaa, 0x38, 0xc9, 0x4c, 0x40, 0xf4, 0xce, 0xdf, 0xf1, 0xb1,
	0x7d, 0xce, 0xb1, 0xfd, 0xc1, 0x1e, 0xcb, 0xb8, 0x0a, 0x96, 0xc7, 0x41, 0x8e, 0x4a, 0x16, 0x79,
	0x84, 0x7e, 0x96, 0x4b, 0x2d, 0xc9, 0xb0, 0xc4, 0xfd, 0xe5, 0xf1, 0xe8, 0xaf, 0x58, 0xca, 0x38,
	0xc1, 0xc0, 0xc0, 0xf3, 0xe2, 0x2e, 0xd0, 0x3c, 0x45, 0xa5, 0x59, 0x9a, 0x55, 0xcc, 0xc9, 0xf7,
	0x0e, 0xd8, 0xb4, 0x5e, 0x4c, 0x0e, 0x61, 0x18, 0x25, 0x85, 0xd2, 0x98, 0x7b, 0x9d, 0x71, 0x67,
	0xea, 0x9e, 0xec, 0xf8, 0xf5, 0x46, 0xfe, 0x45, 0x85, 0x5f, 0x6d, 0xd0, 0x86, 0x42, 0xc6, 0xd0,
	0x55, 0x0f, 0x89, 0x67, 0x19, 0xe6, 0xe6, 0x8a, 0x39, 0x7b, 0x48, 0xae, 0x36, 0x68, 0x39, 0x45,
	0x0e, 0xc0, 0x5a, 0xa6, 0x5e, 0xd7, 0x10, 0xdc, 0x15, 0xe1, 0x26, 0xbd, 0xda, 0xa0, 0xd6, 0x32,
	0x25, 0x6f, 0xc0, 0xc9, 0x58, 0xa1, 0x70, 0x11, 0x32, 0xed, 0xf5, 0x0c, 0x6b, 0xe4, 0x57, 0x82,
	0xfd, 0x46, 0xb0, 0xff, 0xa1, 0x11, 0x4c, 0xed, 0x8a, 0x7c, 0xa6, 0xcf, 0x5d, 0x70, 0x54, 0x86,
	0x11, 0xbf, 0xe3, 0x98, 0x4f, 0x7e, 0xf6, 0x61, 0x58, 0xab, 0x23, 0x1e, 0x0c, 0xb3, 0x5c, 0x7e,
	0xc2, 0x48, 0x1b, 0x03, 0x0e, 0x6d, 0x4a, 0x42, 0xa0, 0x27, 0x58, 0x8a, 0x46, 0xad, 0x43, 0xcd,
	0x98, 0x8c, 0xc0, 0x4e, 0x64, 0xc4, 0x34, 0x97, 0xc2, 0x88, 0x74, 0xe8, 0xaa, 0x26, 0x6f, 0x01,
	0x84, 0x5c, 0x60, 0x98, 0x49, 0x99, 0x28, 0xaf, 0x37, 0xee, 0x4e, 0xdd, 0x93, 0xfd, 0x97, 0x69,
	0xf8, 0xef, 0xe5, 0x02, 0xaf, 0xa5, 0x4c, 0xa8, 0x23, 0xea, 0x91, 0x1a, 0xfd, 0xe8, 0x81, 0xdd,
	0xe0, 0xab, 0x63, 0x3b, 0xad, 0x63, 0xff, 0x83, 0x6d, 0x2e, 0x94, 0x66, 0x22, 0xc2, 0x30, 0xce,
	0x65, 0x91, 0x29, 0xcf, 0x1a, 0x77, 0xa7, 0x0e, 0xdd, 0x6a, 0xe0, 0x4b, 0x83, 0x92, 0x3f, 0xc1,
	0x69, 0xf4, 0x28, 0xaf, 0x6b, 0x28, 0x6b, 0x80, 0x1c, 0x02, 0xe1, 0x82, 0x6b, 0xce, 0x92, 0xd0,
	0x28, 0x8d, 0x64, 0x21, 0xaa, 0x18, 0xfb, 0x74, 0xa7, 0x9e, 0x29, 0x75, 0x5c, 0x94, 0x38, 0xf9,
	0x1b, 0x36, 0xa3, 0x22, 0xcf, 0x51, 0xe8, 0x50, 0xf1, 0x27, 0xf4, 0xfa, 0x86, 0xe7, 0xd6, 0xd8,
	0x8c, 0x3f, 0x21, 0xb9, 0x04, 0x97, 0x15, 0x5a, 0xaa, 0x88, 0x25, 0x5c, 0xc4, 0xde, 0xc0, 0x5c,
	0xc8, 0xbf, 0xbf, 0xf5, 0xec, 0x9f, 0x15, 0x5a, 0xce, 0x2a, 0x32, 0x6d, 0xaf, 0x2c, 0x4d, 0xab,
	0x4c, 0x6a, 0x6f, 0x38, 0xee, 0x4c, 0x6d, 0x6a, 0xc6, 0x64, 0x0c, 0x6e, 0x96, 0x23, 0xa6, 0x99,
	0xe6, 0xf3, 0x04, 0x3d, 0xdb, 0x4c, 0xb5, 0xa1, 0xd1, 0x57, 0x0b, 0xdc, 0xd6, 0x96, 0xe5, 0x5d,
	0xa2, 0x60, 0xf3, 0x04, 0x17, 0x26, 0x3d, 0x9b, 0x36, 0x25, 0xf9, 0x07, 0xb6, 0x52, 0x2e, 0xda,
	0xae, 0x2d, 0xe3, 0x66, 0x33, 0xe5, 0x62, 0xed, 0xb8, 0x64, 0xb1, 0xc7, 0x36, 0xab, 0x5b, 0xb3,
	0xd8, 0xe3, 0x9a, 0x35, 0x85, 0xed, 0x52, 0x7a, 0x96, 0xcb, 0x25, 0x57, 0x5c, 0x0a, 0x5c, 0x98,
	0x08, 0x6d, 0xfa, 0x12, 0x2e, 0xaf, 0xad, 0x09, 0x3f, 0xcc, 0x64, 0xc2, 0xa3, 0x2f, 0x26, 0x44,
	0x87, 0x6e, 0x35, 0xf0, 0xb5, 0x41, 0x49, 0x00, 0xbb, 0x5a, 0x6a, 0x96, 0x84, 0x2f, 0x44, 0x0e,
	0xcc, 0xf1, 0x7f, 0x98, 0xb9, 0x77, 0x6d, 0xa5, 0xeb, 0x05, 0xcf, 0xf5, 0x0e, 0xdb, 0x0b, 0x5a,
	0xa2, 0x27, 0xdf, 0x3a, 0xd0, 0x9d, 0x3d, 0xbc, 0xfe, 0xba, 0x5a, 0x5f, 0xc0, 0x7a, 0xfe, 0x05,
	0xf6, 0x60, 0x90, 0x63, 0xbc, 0x7e, 0xec, 0x75, 0x45, 0xf6, 0xc1, 0x8e, 0x23, 0x0c, 0x9f, 0xa4,
	0x40, 0xe3, 0xdd, 0xa1, 0xc3, 0x38, 0xc2, 0x5b, 0x29, 0x90, 0x1c, 0x00, 0x70, 0x15, 0xe6, 0x85,
	0x10, 0xe5, 0x8b, 0xe8, 0x9b, 0x60, 0x1c, 0xae, 0x68, 0x05, 0x90, 0xff, 0x61, 0x67, 0xc1, 0x34,
	0x9b, 0x33, 0x85, 0xe1, 0x12, 0xf3, 0x32, 0x28, 0xe3, 0xd2, 0xa1, 0xdb, 0x0d, 0x7e, 0x53, 0xc1,
	0x93, 0x8f, 0x60, 0xdd, 0xa4, 0xaf, 0x0a, 0x26, 0xd0, 0x33, 0x47, 0xd7, 0x3f, 0xb3, 0x1c, 0x93,
	0x5d, 0xe8, 0x2b, 0xcd, 0x34, 0xd6, 0x4a, 0xab, 0xa2, 0x6d, 0xad, 0xf7, 0xcc, 0xda, 0xf9, 0xe9,
	0xed, 0x71, 0xcc, 0xf5, 0x7d, 0x31, 0xf7, 0x23, 0x99, 0x06, 0x4b, 0x8e, 0x9a, 0x89, 0xfb, 0x45,
	0x21, 0x45, 0x1c, 0x98, 0xa6, 0x71, 0x14, 0x7f, 0xc6, 0xa3, 0xba, 0x6f, 0x05, 0x75, 0xcf, 0x9c,
	0x0f, 0x4c, 0x8f, 0x39, 0xfd, 0x15, 0x00, 0x00, 0xff, 0xff, 0x2b, 0xc9, 0x26, 0xe1, 0x45, 0x05,
	0x00, 0x00,
}
